---
- hosts: test-servers
  gather_facts: yes
  become: false
  tasks:

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"

  - name: copy file sssd file
    remote_user: root
    ansible.builtin.template:
      src: /root/ansible/sssd.conf_rhel7.j2
      dest: /root/cc.txt
      owner: root
      group: root
      mode: 0644
      backup: yes
    when: ansible_distribution_major_version == '7'

