---
- hosts: nfs-clients
  remote_user: root 
  become: yes
  vars:
    nfsmounts:
      - {  path: "/u01", src: "10.2.36.35:/u01" }
#      - {  path: "/SharedStorage", src: "10.2.30.90:/SharedStorage" }
#      - {  path: "/u02", src: "10.2.28.66:/u02" }
#      - {  path: "/mnt/nfs_mount_2", src: "10.2.30.32:/nfsshare_2" }
  tasks:
   - name: install nfs-utils
     yum: name=nfs-utils state=latest
     ignore_errors: true
    
   - name: service system start
     shell: systemctl restart nfs-utils ;systemctl enable nfs-utils 

   - name: Create a directory to mount the filesystem.
     file:
       path: "{{ item.path }}"
       state: directory
       mode: '0777'
     ignore_errors: true
     with_items: "{{nfsmounts}}"   

   - name: mount the nfsshare in client side
     mount:
       fstype: nfs
       opts: defaults
       dump: 0
       passno: 0
       state: mounted
       src: "{{ item.src }}"
       path: "{{ item.path }}"
     with_items: "{{ nfsmounts }}"
