---
- hosts: rhel7dev
  remote_user: root
  become: true
  tasks:

 # - name: Check if machine is bound
  #  shell: /bin/bash -c "realm list | grep sssd"
  #  register: ad_status
  #  changed_when: false
  #- debug: msg="{{ ad_status.rc }}"
  #  ignore_errors: true

  - name: leaving Realm
    command: /bin/bash -c "realm leave"
  #  when: ad_status.rc == 0
  #  ignore_errors: true

