---
- hosts: test-servers
  remote_user: root
  become: true

  tasks:
  - name: copy package for installation 
    copy:
      dest: "{{ item.dest }}"
      src: "{{ item.src }}"
    with_items:
      - { src: '/root/oracle',dest: '/root' }

  - name: yum update 
    yum: name=* state=latest update_cache=True

  - name: install rpm files 
    yum:
     name: "{{ item }}"
     state: latest
    with_fileglob: 
     - "/root/oracle/*"
